# Generated by Django 5.2.3 on 2025-09-13 18:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_passwordresetotp_reset_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwordresetotp',
            name='reset_token',
        ),
        migrations.AddField(
            model_name='passwordresetotp',
            name='reset_uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True),
        ),
    ]
