# Generated by Django 5.2.3 on 2025-09-13 18:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_passwordresetotp_reset_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetotp',
            name='reset_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
