# Generated by Django 6.0.4 on 2026-05-03 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_passwordresetotp_reset_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_varified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
