# Generated by Django 6.0.4 on 2026-05-03 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_approved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email_varified',
            new_name='email_verified',
        ),
    ]
