# Generated by Django 6.0.4 on 2026-05-03 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_emailverificationotp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='approved',
        ),
        migrations.AddField(
            model_name='user',
            name='countries',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('company_admin', 'Company Admin'), ('team_manager', 'Team Manager'), ('agent', 'Agent')], default='agent', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending_approval', 'Pending Approval')], default='pending_approval', max_length=20),
        ),
    ]
