# Generated by Django 6.0.4 on 2026-05-04 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_user_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='countries',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
