# Generated by Django 6.0.4 on 2026-05-05 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_user_countries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='users.company'),
        ),
        migrations.AlterField(
            model_name='user',
            name='countries',
            field=models.JSONField(default=list),
        ),
    ]
