# Generated by Django 6.0.4 on 2026-05-06 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_user_company_alter_user_countries'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='operating_countries',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
