# Generated by Django 6.0.4 on 2026-05-06 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_company_operating_countries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending_approval', 'Pending Approval'), ('invited', 'Invited')], default='pending_approval', max_length=20),
        ),
    ]
