# Generated by Django 6.0.4 on 2026-05-07 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_team_user_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email_verified',
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('invited', 'Invited')], default='invited', max_length=20),
        ),
    ]
