# Generated by Django 6.0.4 on 2026-05-12 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_lead'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='last_name',
        ),
    ]
