# Generated by Django 6.0.4 on 2026-05-14 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_remove_lead_first_name_remove_lead_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='related_lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='users.lead'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['related_lead'], name='users_task_related_a8ffba_idx'),
        ),
    ]
