# Generated by Django 6.0.4 on 2026-05-14 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_task_related_lead_task_users_task_related_a8ffba_idx'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailVerificationOTP',
        ),
    ]
