# Generated by Django 6.0.4 on 2026-05-14 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_user_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='country',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
