# Generated by Django 6.0.4 on 2026-05-15 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_lead_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_country',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
