# Generated by Django 6.0.4 on 2026-05-20 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_rename_developmentportfolio_project'),
        ('users', '0030_user_current_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='projects.project'),
        ),
    ]
