# Generated by Django 6.0.4 on 2026-05-22 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_projectdocument'),
        ('users', '0033_lead_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='visible_projects',
            field=models.ManyToManyField(blank=True, related_name='visible_to_companies', to='projects.project'),
        ),
    ]
