# Generated by Django 6.0.4 on 2026-06-05 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_remove_company_visible_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='estimated_budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
