# Generated by Django 5.2.7 on 2026-06-09 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_lead_estimated_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='associated_country',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='task',
            name='associated_country',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
