# Generated by Django 5.2.7 on 2026-06-19 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_lead_associated_country_task_associated_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='associated_country',
            new_name='desired_country',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='company',
        ),
        migrations.AddField(
            model_name='lead',
            name='category',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lead',
            name='desired_location',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lead',
            name='other_type',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lead',
            name='type',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
