# Generated by Django 5.2.7 on 2026-06-19 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_rename_associated_country_lead_desired_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='category',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='lead',
            name='desired_location',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='lead',
            name='other_type',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='lead',
            name='type',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
