# Generated by Django 5.2.7 on 2026-06-19 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_alter_lead_category_alter_lead_desired_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
