# Generated by Django 5.2.7 on 2026-07-09 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0029_project_estimated_completion'),
        ('users', '0040_alter_lead_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='projects',
            field=models.ManyToManyField(blank=True, related_name='leads_multi', to='projects.project'),
        ),
    ]
