# Generated by Django 5.2.7 on 2026-07-17 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0041_lead_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('axiyon_admin', 'Axiyon Admin'), ('company_admin', 'Company Admin'), ('team_manager', 'Team Manager'), ('agent', 'Agent')], default='agent', max_length=20),
        ),
    ]
