# Generated by Django 6.0.4 on 2026-07-17 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0042_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='is_assign',
            field=models.BooleanField(default=False),
        ),
    ]
