# Generated by Django 5.2.7 on 2026-07-30 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calling_agent', '0002_remove_call_raw_transcript_delete_task'),
        ('users', '0044_backfill_lead_is_assign'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='related_call',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='calling_agent.call'),
        ),
    ]
