# Generated by Django 5.2.7 on 2026-08-12 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calling_agent', '0008_task_callback_scheduling'),
        ('users', '0045_task_related_call'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='type',
            field=models.CharField(blank=True, choices=[('callback', 'Callback')], max_length=32, null=True),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['scheduled_at'], name='users_task_schedul_42245b_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['type', 'scheduled_at'], name='users_task_type_727a0a_idx'),
        ),
    ]
