# Generated by Django 5.2.7 on 2026-08-21 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0046_task_callback_scheduling'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='expiry_warning_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('expired', 'Expired')], default='pending', max_length=20),
        ),
    ]
