# Generated by Django 5.2.7 on 2026-08-24 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0047_task_expiry_warning_sent_alter_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='expiry_24h_warning_sent',
            field=models.BooleanField(default=False),
        ),
    ]
