# Generated by Django 5.2.7 on 2026-08-24 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0048_merge_lead_status_and_task_expiry'),
        ('users', '0048_task_expiry_24h_warning_sent'),
    ]

    operations = [
    ]
