# Generated by Django 5.2.7 on 2026-08-24 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0049_merge_20260824_1346'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='lead',
            new_name='users_lead_do_not__c099ff_idx',
            old_name='users_lead_do_not_c_idx',
        ),
    ]
