# Generated by Django 5.2.7 on 2026-10-02 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0057_task_open_ended"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="billing_interval",
            field=models.CharField(
                blank=True,
                choices=[("monthly", "Monthly"), ("annual", "Annual")],
                default="",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="current_period_end",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="grace_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="plan",
            field=models.CharField(
                choices=[
                    ("basic", "Basic"),
                    ("professional", "Professional"),
                    ("manual", "Manual"),
                ],
                default="manual",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending_payment", "Pending Payment"),
                    ("active", "Active"),
                    ("past_due", "Past Due"),
                    ("canceled", "Canceled"),
                    ("suspended", "Suspended"),
                ],
                default="active",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="stripe_customer_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="company",
            name="stripe_subscription_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
