# Generated by Django 5.2.7 on 2026-10-02 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0058_company_billing_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProcessedStripeEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_id", models.CharField(max_length=255, unique=True)),
                (
                    "event_type",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("processed_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Processed Stripe event",
                "verbose_name_plural": "Processed Stripe events",
                "ordering": ["-processed_at"],
            },
        ),
        migrations.CreateModel(
            name="CreditCharge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_id", models.CharField(max_length=255, unique=True)),
                ("kind", models.CharField(max_length=50)),
                ("cost", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credit_charges",
                        to="users.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Credit charge",
                "verbose_name_plural": "Credit charges",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UsageCounter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("users", "Users"),
                            ("team_managers", "Team Managers"),
                            ("ai_proposals", "AI Proposals"),
                            ("ai_credits", "AI Credits"),
                        ],
                        max_length=50,
                    ),
                ),
                ("period_start", models.DateTimeField()),
                ("used", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_counters",
                        to="users.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Usage counter",
                "verbose_name_plural": "Usage counters",
                "ordering": ["company", "kind", "-period_start"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("company", "kind", "period_start"),
                        name="unique_usage_counter_per_period",
                    )
                ],
            },
        ),
    ]
