# Generated by Django 5.2.7 on 2026-06-16 20:56

import django.db.models.deletion
import new_proposal.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0022_projectdocument_extracted_at_and_more'),
        ('users', '0037_lead_associated_country_task_associated_country'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=new_proposal.models._proposal_upload_path)),
                ('hosted_url', models.URLField(blank=True, default='', max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_proposals', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_proposals', to='users.lead')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_proposals', to='projects.project')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_proposals', to='projects.unit')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
