# Generated by Django 5.2.7 on 2026-06-17 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_proposal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedproposal',
            name='ai_facts',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
