# Generated by Django 5.2.7 on 2026-06-17 06:42

import new_proposal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_proposal', '0002_generatedproposal_ai_facts'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedproposal',
            name='error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='generatedproposal',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='generatedproposal',
            name='task_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='generatedproposal',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=new_proposal.models._proposal_upload_path),
        ),
    ]
