# Generated by Django 5.2.7 on 2026-06-17 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_proposal', '0003_generatedproposal_error_generatedproposal_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedproposal',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
