# Generated by Django 6.0.4 on 2026-05-15 07:50

import projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DevelopmentPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('developer', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('ready', 'Ready'), ('planned', 'Planned')], default='planned', max_length=20)),
                ('units', models.PositiveIntegerField()),
                ('starting_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('yield_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('image', models.ImageField(upload_to=projects.models.project_image_upload_path)),
                ('project_type', models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('hospitality', 'Hospitality')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
