# Generated by Django 6.0.4 on 2026-05-15 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='developmentportfolio',
            name='units',
        ),
    ]
