# Generated by Django 6.0.4 on 2026-05-15 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='projects.developmentportfolio'),
        ),
    ]
