# Generated by Django 6.0.4 on 2026-05-20 11:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_portfolioagentassignment'),
        ('users', '0030_user_current_country'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DevelopmentPortfolio',
            new_name='Project',
        ),
    ]
