# Generated by Django 6.0.4 on 2026-05-20 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_alter_project_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectAgentAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_split', models.DecimalField(decimal_places=2, max_digits=5)),
                ('company_split', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='portfolioagentassignment',
            name='unique_agent_portfolio',
        ),
        migrations.AddField(
            model_name='projectagentassignment',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectagentassignment',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_assignments', to='projects.project'),
        ),
        migrations.RemoveField(
            model_name='portfolioagentassignment',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='portfolioagentassignment',
            name='portfolio',
        ),
        migrations.AddConstraint(
            model_name='projectagentassignment',
            constraint=models.UniqueConstraint(fields=('agent', 'project'), name='unique_agent_project_assignment'),
        ),
        migrations.DeleteModel(
            name='PortfolioAgentAssignment',
        ),
    ]
