# Generated by Django 6.0.4 on 2026-06-01 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_project_image_json_and_remove_projectimage'),
        ('users', '0035_remove_company_visible_projects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='visible_to_company',
        ),
        migrations.AddField(
            model_name='project',
            name='visible_to_companies',
            field=models.ManyToManyField(blank=True, related_name='visible_projects', to='users.company'),
        ),
    ]
