# Generated by Django 6.0.4 on 2026-06-02 12:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_remove_project_visible_to_company_and_more'),
        ('users', '0035_remove_company_visible_projects'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('input_file', models.FileField(upload_to='proposals/input/')),
                ('output_file', models.FileField(blank=True, null=True, upload_to='proposals/output/')),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='uploaded', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='users.lead')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='projects.unit')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
