# Generated by Django 6.0.4 on 2026-06-06 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_proposal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Proposal',
        ),
    ]
