# Generated by Django 5.2.7 on 2026-06-09 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_delete_proposal'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='associated_country',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='unit',
            name='associated_country',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
