# Generated by Django 6.0.4 on 2026-06-09 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_project_associated_country_unit_associated_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='area',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='price',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='unit_type',
        ),
        migrations.AddField(
            model_name='unit',
            name='area_ft2',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Area in square feet', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='area_m2',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Area in square meters', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='category',
            field=models.CharField(blank=True, default='', help_text='e.g., 1 Bed, 2 Bed, Studio', max_length=100),
        ),
        migrations.AddField(
            model_name='unit',
            name='floor',
            field=models.CharField(blank=True, default='', help_text='e.g., Ground Floor, 1st Floor', max_length=100),
        ),
        migrations.AddField(
            model_name='unit',
            name='list_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Original/List price', max_digits=12),
            preserve_default=False,
        ),
    ]
