# Generated by Django 6.0.4 on 2026-06-09 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_remove_unit_area_remove_unit_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='bed_1',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='bed_2',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='number_of_units',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='property_category',
            field=models.CharField(blank=True, choices=[('apartment', 'Apartment'), ('villa', 'Villa'), ('studio', 'Studio'), ('townhouse', 'Townhouse'), ('penthouse', 'Penthouse'), ('duplex', 'Duplex'), ('office', 'Office'), ('retail', 'Retail')], default='', max_length=20),
        ),
    ]
