# Generated by Django 6.0.4 on 2026-06-09 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_project_bed_1_project_bed_2_project_number_of_units_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='property_category',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
