# Generated by Django 5.2.7 on 2026-06-16 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_alter_project_property_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdocument',
            name='extracted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectdocument',
            name='extracted_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
