# Generated by Django 5.2.7 on 2026-06-17 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0022_projectdocument_extracted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='proposal_ai_facts',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='project',
            name='proposal_assets_fingerprint',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='project',
            name='proposal_cover_image',
            field=models.FileField(blank=True, null=True, upload_to='project_proposal_assets/'),
        ),
        migrations.AddField(
            model_name='project',
            name='proposal_logo_image',
            field=models.FileField(blank=True, null=True, upload_to='project_proposal_assets/'),
        ),
    ]
