# Generated by Django 5.2.7 on 2026-06-19 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0024_project_proposal_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_status',
            field=models.CharField(default='draft', max_length=20),
        ),
    ]
