# Generated by Django 5.2.7 on 2026-06-22 12:01

import projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0025_project_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='floor_plan_image',
            field=models.ImageField(blank=True, help_text='Floor plan image for this unit', null=True, upload_to=projects.models.unit_floor_plan_upload_path),
        ),
    ]
