# Generated by Django 5.2.7 on 2026-07-01 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0027_unit_discounted_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='bed_3',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='studio',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='bed_1',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='bed_2',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='number_of_units',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
