# Generated by Django 5.2.7 on 2026-07-08 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0028_project_bed_3_project_studio_alter_project_bed_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='estimated_completion',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
