# Generated by Django 5.2.7 on 2026-07-16 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0029_project_estimated_completion'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='est_market_rent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Estimated market rent (PCM, optional)', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='est_yield_gross',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Estimated gross yield in % (optional)', max_digits=6, null=True),
        ),
    ]
