# Generated by Django 5.2.7 on 2026-06-15 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='proposal_draft',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ChatUploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='chatbot/uploads/')),
                ('file_type', models.CharField(choices=[('brochure', 'Brochure'), ('supporting', 'Supporting')], max_length=20)),
                ('original_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to='chatbot.chatsession')),
            ],
        ),
    ]
