# Generated by Django 5.2.7 on 2026-06-24 10:37

import uuid
from django.db import migrations, models


def populate_thread_ids(apps, schema_editor):
    """Assign a unique UUID to every existing ChatSession row."""
    ChatSession = apps.get_model('chatbot', 'ChatSession')
    for session in ChatSession.objects.all():
        session.thread_id = uuid.uuid4()
        session.save(update_fields=['thread_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_add_proposal_draft_and_uploaded_file'),
    ]

    operations = [
        # Step 1: add without unique constraint so existing rows can be populated
        migrations.AddField(
            model_name='chatsession',
            name='thread_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        # Step 2: populate each existing row with a distinct UUID
        migrations.RunPython(populate_thread_ids, migrations.RunPython.noop),
        # Step 3: now enforce unique + non-null
        migrations.AlterField(
            model_name='chatsession',
            name='thread_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
