# Generated by Django 5.2.7 on 2026-06-24 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_chatsession_thread_id_chatsession_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatuploadedfile',
            name='session',
        ),
        migrations.RemoveField(
            model_name='chatsession',
            name='proposal_draft',
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
        migrations.DeleteModel(
            name='ChatUploadedFile',
        ),
    ]
