# Generated by Django 5.2.7 on 2026-06-26 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0005_knowledgebasedocument'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='knowledgebasedocument',
            name='char_count',
        ),
        migrations.RemoveField(
            model_name='knowledgebasedocument',
            name='extracted_text',
        ),
        migrations.RemoveField(
            model_name='knowledgebasedocument',
            name='metadata',
        ),
    ]
