# Generated by Django 5.2.7 on 2026-06-26 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0006_remove_knowledgebasedocument_char_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgebasedocument',
            name='associated_country',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
