# Generated by Django 5.2.7 on 2026-06-26 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0007_knowledgebasedocument_associated_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgebasedocument',
            name='hosted_url',
            field=models.URLField(blank=True, default='', max_length=1000),
        ),
    ]
