# Generated by Django 5.2.7 on 2026-07-30 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(default='Sarah Wilson', max_length=255)),
                ('lead_name', models.CharField(default='Ameera Al-Sayed', max_length=255)),
                ('phone_number', models.CharField(default='+447911123456', max_length=32)),
                ('duration', models.CharField(default='02:28', max_length=20)),
                ('status', models.CharField(choices=[('ENDED', 'Ended'), ('ARCHIVED', 'Archived'), ('IN_PROGRESS', 'In Progress'), ('FAILED', 'Failed')], default='ENDED', max_length=20)),
                ('recording_url', models.CharField(blank=True, default='', max_length=500)),
                ('transcript_data', models.JSONField(blank=True, default=list)),
                ('raw_transcript', models.TextField(blank=True, default='')),
                ('summary', models.TextField(blank=True, default='')),
                ('key_sentiments', models.JSONField(blank=True, default=list)),
                ('detected_intents', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('priority', models.CharField(default='Medium', max_length=50)),
                ('category', models.CharField(default='General', max_length=100)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('due_date_label', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='calling_agent.call')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
