# Generated by Django 5.2.7 on 2026-07-30 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calling_agent', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='call',
            name='raw_transcript',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
