# Generated by Django 5.2.7 on 2026-07-30 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calling_agent', '0002_remove_call_raw_transcript_delete_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='call',
            name='customer_name',
        ),
        migrations.AlterField(
            model_name='call',
            name='status',
            field=models.CharField(choices=[('ENDED', 'Ended'), ('SUCCESSFUL', 'Successful'), ('IN_PROGRESS', 'In Progress'), ('FAILED', 'Failed')], default='SUCCESSFUL', max_length=20),
        ),
    ]
