# Generated by Django 5.2.7 on 2026-08-03 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calling_agent', '0006_callgeneratedaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallTranscriptTurn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turn_index', models.PositiveIntegerField()),
                ('speaker', models.CharField(choices=[('agent', 'Agent'), ('customer', 'Customer'), ('system', 'System'), ('unknown', 'Unknown')], default='unknown', max_length=16)),
                ('message', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcript_turns', to='calling_agent.call')),
            ],
            options={
                'ordering': ['turn_index'],
                'constraints': [models.UniqueConstraint(fields=('call', 'turn_index'), name='unique_call_transcript_turn')],
            },
        ),
        migrations.CreateModel(
            name='CallWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_key', models.CharField(max_length=255, unique=True)),
                ('event_type', models.CharField(choices=[('post_call_transcription', 'Post Call Transcription'), ('post_call_audio', 'Post Call Audio'), ('call_initiation_failure', 'Call Initiation Failure'), ('unknown', 'Unknown')], default='unknown', max_length=64)),
                ('conversation_id', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('body_hash', models.CharField(max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('process_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('ignored', 'Ignored')], default='pending', max_length=16)),
                ('retry_count', models.PositiveSmallIntegerField(default=0)),
                ('last_error', models.CharField(blank=True, default='', max_length=500)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('call', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_events', to='calling_agent.call')),
            ],
            options={
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['process_status', 'received_at'], name='calling_webhook_status_idx')],
            },
        ),
    ]
