# Generated by Django 5.2.7 on 2026-08-12 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calling_agent', '0007_webhook_post_call'),
        ('users', '0045_task_related_call'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='related_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_calls', to='users.task'),
        ),
    ]
