# Generated by Django 5.2.7 on 2026-08-12 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calling_agent', '0008_task_callback_scheduling'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callwebhookevent',
            name='event_type',
            field=models.CharField(
                choices=[
                    ('post_call_transcription', 'Post Call Transcription'),
                    (
                        'post_call_transcription_otel',
                        'Post Call Transcription OTEL',
                    ),
                    ('post_call_audio', 'Post Call Audio'),
                    ('call_initiation_failure', 'Call Initiation Failure'),
                    ('unknown', 'Unknown'),
                ],
                default='unknown',
                max_length=64,
            ),
        ),
    ]
