import logging
import os

from celery.result import AsyncResult
from django.http import FileResponse, Http404
from drf_yasg import openapi
from drf_yasg.utils import swagger_auto_schema
from rest_framework import permissions, status
from rest_framework.response import Response
from rest_framework.views import APIView

from projects.models import Project
from new_proposal.models import GeneratedProposal
from new_proposal.serializers import (
    GeneratedProposalSerializer,
    NewProposalSerializer,
)
from new_proposal.tasks import generate_proposal_pdf_task
from new_proposal.extraction.project_assets import ensure_project_proposal_assets

_TAGS = ["New Proposal"]

logger = logging.getLogger(__name__)

# Create your views here.


class NewProposalView(APIView):
    permission_classes = [permissions.IsAuthenticated]

    @swagger_auto_schema(
        tags=_TAGS,
        manual_parameters=[
            openapi.Parameter("project", openapi.IN_QUERY, type=openapi.TYPE_INTEGER, required=False),
            openapi.Parameter("lead", openapi.IN_QUERY, type=openapi.TYPE_INTEGER, required=False),
            openapi.Parameter("unit", openapi.IN_QUERY, type=openapi.TYPE_INTEGER, required=False),
            openapi.Parameter("mine", openapi.IN_QUERY, type=openapi.TYPE_BOOLEAN, required=False,
                              description="If true, only return proposals generated by the current user."),
        ],
    )
    def get(self, request, *args, **kwargs):
        qs = GeneratedProposal.objects.select_related(
            "project", "lead", "unit", "generated_by"
        ).all()

        project_id = request.query_params.get("project")
        lead_id = request.query_params.get("lead")
        unit_id = request.query_params.get("unit")
        mine = request.query_params.get("mine", "").lower() in ("1", "true", "yes")

        if project_id:
            qs = qs.filter(project_id=project_id)
        if lead_id:
            qs = qs.filter(lead_id=lead_id)
        if unit_id:
            qs = qs.filter(unit_id=unit_id)
        if mine and request.user.is_authenticated:
            qs = qs.filter(generated_by=request.user)
        
        # Filter proposals by matching current user's current_country with project's associated_country
        current_user_country = request.user.current_country
        if current_user_country and str(current_user_country).strip().lower() != "all":
            qs = qs.filter(project__associated_country=current_user_country)

        serializer = GeneratedProposalSerializer(qs, many=True)
        return Response(serializer.data)

    @swagger_auto_schema(
        tags=_TAGS,
        request_body=openapi.Schema(
            type=openapi.TYPE_OBJECT,
            required=["project", "lead", "unit"],
            properties={
                "project": openapi.Schema(type=openapi.TYPE_INTEGER, description="Project ID"),
                "lead": openapi.Schema(type=openapi.TYPE_INTEGER, description="Lead ID"),
                "unit": openapi.Schema(type=openapi.TYPE_INTEGER, description="Unit ID"),
                "force_refresh": openapi.Schema(
                    type=openapi.TYPE_BOOLEAN,
                    description="Optional. If true, re-extract proposal assets and AI facts even if cached.",
                ),
            },
        ),
    )
    def post(self, request, *args, **kwargs):
        serializer = NewProposalSerializer(data=request.data)
        serializer.is_valid(raise_exception=True)

        # Fail fast with 403 + the plan numbers rather than queueing a task that
        # will fail in the background. The worker re-checks authoritatively.
        if request.user.is_authenticated:
            from new_proposal.tasks import check_proposal_quota

            check_proposal_quota(request.user)

        project = serializer.validated_data["project"]
        lead = serializer.validated_data["lead"]
        unit = serializer.validated_data["unit"]
        force_refresh = str(request.data.get("force_refresh", "")).lower() in ("1", "true", "yes")

        proposal = GeneratedProposal.objects.create(
            project=project,
            lead=lead,
            unit=unit,
            generated_by=request.user if request.user.is_authenticated else None,
            status=GeneratedProposal.Status.PENDING,
        )

        async_result = generate_proposal_pdf_task.delay(proposal.pk, force_refresh=force_refresh)
        if async_result and async_result.id:
            GeneratedProposal.objects.filter(pk=proposal.pk).update(
                task_id=async_result.id,
            )

        return Response(
            {
                "proposal_id": proposal.pk,
                "project_id": project.id,
                "lead_id": lead.id,
                "unit_id": unit.id,
                "generated_by": request.user.id if request.user.is_authenticated else None,
                "status": GeneratedProposal.Status.PENDING,
                "task_id": async_result.id if async_result else "",
                "created_at": proposal.created_at,
                "detail": "Proposal generation queued. Poll the GET endpoint until status is 'completed'.",
            },
            status=status.HTTP_202_ACCEPTED,
        )


class GeneratedProposalDetailView(APIView):
    """Retrieve or delete a single GeneratedProposal by id."""

    permission_classes = [permissions.IsAuthenticated]

    def _get_object(self, pk):
        return (
            GeneratedProposal.objects
            .select_related("project", "lead", "unit", "generated_by")
            .filter(pk=pk)
            .first()
        )

    @swagger_auto_schema(tags=_TAGS, operation_summary="Retrieve a generated proposal")
    def get(self, request, pk, *args, **kwargs):
        proposal = self._get_object(pk)
        if proposal is None:
            return Response(
                {"detail": "Proposal not found."},
                status=status.HTTP_404_NOT_FOUND,
            )
        return Response(GeneratedProposalSerializer(proposal).data)

    @swagger_auto_schema(tags=_TAGS, operation_summary="Delete a generated proposal")
    def delete(self, request, pk, *args, **kwargs):
        proposal = self._get_object(pk)
        if proposal is None:
            return Response(
                {"detail": "Proposal not found."},
                status=status.HTTP_404_NOT_FOUND,
            )

        try:
            if proposal.file:
                proposal.file.delete(save=False)
        except Exception as exc:  # noqa: BLE001
            logger.warning(
                "Could not remove stored file for proposal %s: %s", pk, exc,
            )

        proposal.delete()
        return Response(status=status.HTTP_204_NO_CONTENT)


class GeneratedProposalDownloadView(APIView):
    """Stream a generated proposal PDF as an attachment by proposal id."""

    permission_classes = [permissions.IsAuthenticated]

    @swagger_auto_schema(
        tags=_TAGS,
        operation_summary="Download a generated proposal PDF by id",
    )
    def get(self, request, pk, *args, **kwargs):
        proposal = (
            GeneratedProposal.objects
            .filter(pk=pk)
            .first()
        )
        if proposal is None:
            return Response(
                {"detail": "Proposal not found."},
                status=status.HTTP_404_NOT_FOUND,
            )

        if proposal.status != GeneratedProposal.Status.COMPLETED:
            return Response(
                {
                    "detail": "Proposal is not ready yet.",
                    "status": proposal.status,
                },
                status=status.HTTP_409_CONFLICT,
            )

        if not proposal.file:
            return Response(
                {"detail": "Proposal file is missing."},
                status=status.HTTP_404_NOT_FOUND,
            )

        filename = os.path.basename(proposal.file.name) or f"proposal_{proposal.pk}.pdf"

        try:
            file_handle = proposal.file.open("rb")
        except Exception as exc:  # noqa: BLE001
            logger.exception("Could not open proposal %s file: %s", pk, exc)
            raise Http404("Proposal file could not be opened.") from exc

        response = FileResponse(
            file_handle,
            as_attachment=True,
            filename=filename,
            content_type="application/pdf",
        )
        return response


class ProposalTaskStatusView(APIView):
    """Check the Celery task status for a queued / running proposal."""

    permission_classes = [permissions.IsAuthenticated]

    @swagger_auto_schema(
        tags=_TAGS,
        operation_summary="Get proposal task status by Celery task id",
    )
    def get(self, request, task_id, *args, **kwargs):
        result = AsyncResult(task_id)
        proposal = (
            GeneratedProposal.objects
            .select_related("project", "lead", "unit", "generated_by")
            .filter(task_id=task_id)
            .first()
        )

        payload = {
            "task_id": task_id,
            "task_state": result.state,
            "task_ready": result.ready(),
            "task_successful": result.successful() if result.ready() else None,
            "task_result": result.result if result.ready() and not isinstance(result.result, Exception) else None,
        }

        if proposal is not None:
            payload["proposal"] = GeneratedProposalSerializer(proposal).data
        else:
            payload["proposal"] = None

        return Response(payload)
