# Generated by Django 5.2.7 on 2026-07-02 18:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_instance', models.CharField(max_length=100)),
                ('api_token_instance', models.CharField(max_length=255)),
                ('api_url', models.CharField(blank=True, default='', max_length=255)),
                ('media_url', models.CharField(blank=True, default='', max_length=255)),
                ('phone_number', models.CharField(blank=True, default='', max_length=32)),
                ('state', models.CharField(choices=[('notAuthorized', 'Not Authorized'), ('authorized', 'Authorized'), ('blocked', 'Blocked'), ('sleepMode', 'Sleep Mode'), ('starting', 'Starting'), ('yellowCard', 'Yellow Card'), ('unknown', 'Unknown')], default='unknown', max_length=32)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WhatsAppChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=128)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('is_group', models.BooleanField(default=False)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='whatsapp.whatsappaccount')),
            ],
            options={
                'ordering': ['-last_message_at', '-updated_at'],
                'unique_together': {('account', 'chat_id')},
            },
        ),
        migrations.CreateModel(
            name='WhatsAppMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=128)),
                ('direction', models.CharField(choices=[('in', 'Incoming'), ('out', 'Outgoing')], max_length=8)),
                ('type', models.CharField(blank=True, default='', max_length=32)),
                ('text', models.TextField(blank=True, default='')),
                ('sender_id', models.CharField(blank=True, default='', max_length=128)),
                ('sender_name', models.CharField(blank=True, default='', max_length=255)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='whatsapp.whatsappchat')),
            ],
            options={
                'ordering': ['-timestamp'],
                'unique_together': {('chat', 'message_id')},
            },
        ),
    ]
