# Generated by Django 5.2.7 on 2026-07-07 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappmessage',
            name='caption',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='file_name',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='media_url',
            field=models.URLField(blank=True, default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='mime_type',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
