# Generated by Django 5.2.7 on 2026-08-03 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0002_whatsappmessage_caption_whatsappmessage_file_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappaccount',
            name='last_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='whatsappaccount',
            name='provider',
            field=models.CharField(default='waha', max_length=32),
        ),
        migrations.AddField(
            model_name='whatsappaccount',
            name='qr_code',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='whatsappaccount',
            name='session_name',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='whatsappaccount',
            name='session_status',
            field=models.CharField(blank=True, default='not_created', max_length=32),
        ),
        migrations.AlterField(
            model_name='whatsappaccount',
            name='api_token_instance',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='whatsappaccount',
            name='id_instance',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
