# Generated by Django 5.2.7 on 2026-08-03 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0003_whatsappaccount_last_error_whatsappaccount_provider_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whatsappaccount',
            name='api_token_instance',
        ),
        migrations.RemoveField(
            model_name='whatsappaccount',
            name='api_url',
        ),
        migrations.RemoveField(
            model_name='whatsappaccount',
            name='id_instance',
        ),
        migrations.RemoveField(
            model_name='whatsappaccount',
            name='last_error',
        ),
        migrations.RemoveField(
            model_name='whatsappaccount',
            name='last_synced_at',
        ),
        migrations.RemoveField(
            model_name='whatsappaccount',
            name='media_url',
        ),
        migrations.RemoveField(
            model_name='whatsappaccount',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='whatsappaccount',
            name='state',
        ),
    ]
