# Generated by Django 5.2.7 on 2026-08-03 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0004_remove_whatsappaccount_api_token_instance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whatsappaccount',
            name='qr_code',
        ),
    ]
