# Generated by Django 5.2.7 on 2026-08-07 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0006_whatsappsynclog'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappchat',
            name='profile_picture',
            field=models.URLField(blank=True, default='', max_length=1024),
        ),
    ]
