# Generated by Django 5.2.7 on 2026-08-08 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0007_whatsappchat_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappaccount',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='whatsappaccount',
            name='number',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='whatsappaccount',
            name='profile_picture',
            field=models.URLField(blank=True, default='', max_length=1024),
        ),
    ]
