# Generated by Django 5.2.7 on 2026-08-08 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0008_whatsappaccount_name_whatsappaccount_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappaccount',
            name='media_api_key',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
