# Generated by Django 5.2.7 on 2026-08-09 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0009_whatsappaccount_media_api_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppDeletedMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(db_index=True, max_length=128)),
                ('message_id', models.CharField(db_index=True, max_length=128)),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deleted_messages', to='whatsapp.whatsappaccount')),
            ],
            options={
                'ordering': ['-deleted_at'],
                'unique_together': {('account', 'chat_id', 'message_id')},
            },
        ),
    ]
