# Generated by Django 5.2.7 on 2026-08-09 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0010_whatsappdeletedmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappmessage',
            name='ack',
            field=models.CharField(choices=[('ERROR', 'Error'), ('PENDING', 'Pending'), ('SERVER', 'Sent'), ('DEVICE', 'Delivered'), ('READ', 'Read'), ('PLAYED', 'Played')], db_index=True, default='PENDING', max_length=16),
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='ack_code',
            field=models.IntegerField(default=1),
        ),
    ]
