# Generated by Django 5.2.7 on 2026-08-14 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0011_whatsappmessage_ack_whatsappmessage_ack_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappmessage',
            name='reaction',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
