# Generated by Django 5.2.7 on 2026-08-14 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0012_whatsappmessage_reaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappmessage',
            name='reaction',
            field=models.CharField(blank=True, default='', max_length=64, null=True),
        ),
    ]
