# Generated by Django 5.2.7 on 2026-08-14 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0013_alter_whatsappmessage_reaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WhatsAppSyncLog',
        ),
    ]
