# Generated by Django 5.2.7 on 2026-08-20 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0014_delete_whatsappsynclog'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappchat',
            name='unread_count',
            field=models.IntegerField(default=0),
        ),
    ]
