from django.urls import path

from whatsapp.views import (
    WhatsAppDeleteAllMessagesView,
    WhatsAppDeleteChatView,
    WhatsAppDeleteMessageView,
    WhatsAppGetChatMessagesView,
    WhatsAppMarkChatReadView,
    WhatsAppGetChatsView,
    WhatsAppQrView,
    WhatsAppSendMessageView,
    WhatsAppStateView,
    WhatsAppSyncView,
    WhatsAppSyncStatusView,
    WhatsAppWebhookView,
    WhatsAppLogoutView,
    WhatsAppProfileView,
    WhatsAppProfileNameView,
    WhatsAppProfilePictureView,
    WhatsAppMediaProxyView,
    WhatsAppCheckNumberExistsView,
    WhatsAppSaveContactView,
    WhatsAppGetAllContactsView,
    WhatsAppReactionView,
)

urlpatterns = [
    path("qr/", WhatsAppQrView.as_view(), name="whatsapp-qr"),
    path("state/", WhatsAppStateView.as_view(), name="whatsapp-state"),
    path("sync/", WhatsAppSyncView.as_view(), name="whatsapp-sync"),
    path("sync/status/", WhatsAppSyncStatusView.as_view(), name="whatsapp-sync-status"),
    path("logout/", WhatsAppLogoutView.as_view(), name="whatsapp-logout"),
    path("send-text/", WhatsAppSendMessageView.as_view(), name="whatsapp-send-text"),
    path("reaction/", WhatsAppReactionView.as_view(), name="whatsapp-reaction"),
    path("chats/", WhatsAppGetChatsView.as_view(), name="whatsapp-get-chats"),
    path("chats/<str:chat_id>/messages/", WhatsAppGetChatMessagesView.as_view(), name="whatsapp-get-chat-messages"),
    path("chats/<str:chat_id>/read/", WhatsAppMarkChatReadView.as_view(), name="whatsapp-mark-chat-read"),
    path("chats/<str:chat_id>/", WhatsAppDeleteChatView.as_view(), name="whatsapp-delete-chat"),
    path("chats/<str:chat_id>/messages/<str:message_id>/", WhatsAppDeleteMessageView.as_view(), name="whatsapp-delete-message"),
    path("chats/<str:chat_id>/delete-messages/", WhatsAppDeleteAllMessagesView.as_view(), name="whatsapp-delete-all-messages"),
    path("contacts/check-exists/", WhatsAppCheckNumberExistsView.as_view(), name="whatsapp-check-number-exists"),
    path("contacts/save/", WhatsAppSaveContactView.as_view(), name="whatsapp-save-contact"),
    path("contacts/all/", WhatsAppGetAllContactsView.as_view(), name="whatsapp-get-all-contacts"),
    path("webhook/", WhatsAppWebhookView.as_view(), name="whatsapp-webhook"),
    path("profile/", WhatsAppProfileView.as_view(), name="whatsapp-profile"),
    path("profile/name/", WhatsAppProfileNameView.as_view(), name="whatsapp-profile-name"),
    path("profile/picture/", WhatsAppProfilePictureView.as_view(), name="whatsapp-profile-picture"),
    path("media-proxy/", WhatsAppMediaProxyView.as_view(), name="whatsapp-media-proxy"),
]

