# Generated by Django 5.2.7 on 2026-07-06 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('lead_assigned_no_commission', 'Lead Assigned Without Commission'), ('unit_missing_proposal_images', 'Unit Missing Proposal Images'), ('generic', 'Generic')], default='generic', max_length=64),
        ),
    ]
