# Generated by Django 5.2.7 on 2026-08-24 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_alter_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('lead_assigned_no_commission', 'Lead Assigned Without Commission'), ('unit_missing_proposal_images', 'Unit Missing Proposal Images'), ('lead_project_missing_images', 'Lead Project Missing Proposal Images'), ('task_expiring_soon', 'Task Expiring Soon'), ('task_expiring_after_24h', 'Task Expiring After 24 Hours'), ('task_expired', 'Task Expired'), ('generic', 'Generic')], default='generic', max_length=64),
        ),
    ]
