"""
Django settings for API project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from datetime import timedelta
from pathlib import Path

from corsheaders.defaults import default_methods
from decouple import Csv
from decouple import config


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', cast=Csv())


# Application definition

INSTALLED_APPS = [
    'daphne',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-party apps
    'drf_yasg',
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'django_filters',
    'channels',

    # Local apps
    'users',
    'projects',
    'chatbot',
    'new_proposal',
    'notifications',
    'whatsapp',
    'calling_agent',
    'billing',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # 'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    # Global subscription enforcement. Sits after AuthenticationMiddleware so
    # session users are resolved, and before the view so a company that cannot
    # pay is rejected before any work happens.
    'billing.middleware.SubscriptionGuardMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'api.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'api.wsgi.application'
ASGI_APPLICATION = 'api.asgi.application'

# ── Channels (WebSocket) channel layer ──────────────────────────────────────
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            'hosts': [config('REDIS_URL', default='redis://localhost:6379/1')],
        },
    },
}


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases


DATABASES = {
    "default": {
        "ENGINE": config("DB_ENGINE"),
        "NAME": config("DB_NAME"),
        "USER": config("DB_USER", default=None),
        "PASSWORD": config("DB_PASSWORD", default=None),
        "HOST": config("DB_HOST", default=None),
        "PORT": config("DB_PORT", default=None),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / "staticfiles" if DEBUG else "/var/www/project/static"

STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.StaticFilesStorage'

# # For better compression
# if DEBUG:
#     STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.StaticFilesStorage'
# else:
#     STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# ── Media file storage ──────────────────────────────────────────────────────
# Set USE_S3=False in your .env to use local disk storage for development.
USE_S3 = config('USE_S3', default=False, cast=bool)

if USE_S3:
    AWS_ACCESS_KEY_ID = config('AWS_ACCESS_KEY_ID')
    AWS_SECRET_ACCESS_KEY = config('AWS_SECRET_ACCESS_KEY')
    AWS_STORAGE_BUCKET_NAME = config('AWS_STORAGE_BUCKET_NAME')
    AWS_S3_REGION_NAME = config('AWS_S3_REGION_NAME', default='us-east-1')

    STORAGES = {
        'default': {
            'BACKEND': 'api.storage.TimeoutS3Storage',
            'OPTIONS': {
                'bucket_name': AWS_STORAGE_BUCKET_NAME,
                'region_name': AWS_S3_REGION_NAME,
                'location': 'media',
                'querystring_auth': False,
            }
        },
        'staticfiles': {
            'BACKEND': 'django.contrib.staticfiles.storage.StaticFilesStorage',
        },
    }

    MEDIA_URL = f'https://{AWS_STORAGE_BUCKET_NAME}.s3.{AWS_S3_REGION_NAME}.amazonaws.com/media/'
else:
    MEDIA_URL = '/media/'
    MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

    STORAGES = {
        'default': {
            'BACKEND': 'django.core.files.storage.FileSystemStorage',
        },
        'staticfiles': {
            'BACKEND': 'django.contrib.staticfiles.storage.StaticFilesStorage',
        },
    }

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CUSTOM
AUTH_USER_MODEL = 'users.User'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
        # Runs after IsAuthenticated, so it only ever sees an authenticated
        # request. Blocks companies whose billing is not in good standing.
        'billing.guards.SubscriptionGuard',
    ],
    # Gives 402/403 billing errors their machine-readable body shape.
    'EXCEPTION_HANDLER': 'billing.exception_handlers.billing_exception_handler',
}

# Prefix stripped from request paths when matching billing-exempt routes.
API_URL_PREFIXES = ('/api/',)

SWAGGER_SETTINGS = {
    'SECURITY_DEFINITIONS': {
        'Bearer': {
            'type': 'apiKey',
            'name': 'Authorization',
            'in': 'header'
        }
    },
    'USE_SESSION_AUTH': False,
    'PERSIST_AUTH': True,

    'DEEP_LINKING': True,
    'DOC_EXPANSION': "list",
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(days=1),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "SIGNING_KEY": SECRET_KEY
}


LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },
}

# CORS
CORS_ALLOWED_ORIGINS = config("CORS_ALLOWED_ORIGINS", cast=Csv())

CORS_ALLOW_METHODS = list(default_methods)

CORS_ALLOW_CREDENTIALS = True

CSRF_TRUSTED_ORIGINS = config("CSRF_TRUSTED_ORIGINS", cast=Csv())
SESSION_COOKIE_SAMESITE = "None"
SESSION_COOKIE_SECURE = True    # required when SameSite=None

# CORS_ALLOW_HEADERS = list(default_headers) + [
#     "ngrok-skip-browser-warning",
# ]

# EMAIL
EMAIL_BACKEND = config("EMAIL_BACKEND", cast=str, default="django.core.mail.backends.console.EmailBackend")
EMAIL_HOST = config("EMAIL_HOST", cast=str)
EMAIL_PORT = config("EMAIL_PORT", cast=int)
EMAIL_HOST_USER = config("EMAIL_HOST_USER", cast=str)
EMAIL_HOST_PASSWORD = config("EMAIL_HOST_PASSWORD", cast=str)
EMAIL_USE_TLS = config("EMAIL_USE_TLS", cast=bool)
EMAIL_USE_SSL = config("EMAIL_USE_SSL", cast=bool)

DEFAULT_FROM_EMAIL = config("DEFAULT_FROM_EMAIL", cast=str)
FRONTEND_URL = config("FRONTEND_URL", cast=str)
FRONTEND_LOGIN_URL = config("FRONTEND_LOGIN_URL", cast=str)
APP_NAME = config("APP_NAME", cast=str)


# ── Stripe ───────────────────────────────────────────────────────────────────
# No secret or price ID is ever hardcoded; price selection happens server-side
# from these variables so the client can never choose what it pays.
STRIPE_SECRET_KEY = config("STRIPE_SECRET_KEY", cast=str, default="")
STRIPE_WEBHOOK_SECRET = config("STRIPE_WEBHOOK_SECRET", cast=str, default="")
STRIPE_PRICE_PRO_MONTHLY = config("STRIPE_PRICE_PRO_MONTHLY", cast=str, default="")
STRIPE_PRICE_PRO_ANNUAL = config("STRIPE_PRICE_PRO_ANNUAL", cast=str, default="")

# Number of days an unpaid company is kept before cleanup, and the grace period
# a past_due company keeps full access.
BILLING_PENDING_COMPANY_TTL_HOURS = config(
    "BILLING_PENDING_COMPANY_TTL_HOURS",
    default=48,
    cast=int,
)
BILLING_GRACE_PERIOD_DAYS = config(
    "BILLING_GRACE_PERIOD_DAYS",
    default=5,
    cast=int,
)


SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
USE_X_FORWARDED_HOST = True


CELERY_BROKER_URL = config("CELERY_BROKER_URL", cast=str, default='redis://localhost:6379/0')
CELERY_RESULT_BACKEND = config("CELERY_RESULT_BACKEND", cast=str, default='redis://localhost:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'

# Worker resource limits — prevent OOM on small instances (t3.micro: 1 GB RAM)
# Playwright + Chromium needs ~500 MB per task; only run one at a time.
CELERY_WORKER_CONCURRENCY = 1
CELERY_WORKER_PREFETCH_MULTIPLIER = 1
CELERY_TASK_ACKS_LATE = True  # re-queue if worker crashes (OOM)
# Recycle child processes after each task / when RSS exceeds ~600 MB (value is KB).
CELERY_WORKER_MAX_TASKS_PER_CHILD = 1
CELERY_WORKER_MAX_MEMORY_PER_CHILD = 600000

CALLING_AGENT_POLL_INTERVAL_SECONDS = config(
    "CALLING_AGENT_POLL_INTERVAL_SECONDS",
    default=60,
    cast=int,
)
CALLING_AGENT_RECONCILE_INTERVAL_SECONDS = config(
    "CALLING_AGENT_RECONCILE_INTERVAL_SECONDS",
    default=60,
    cast=int,
)
CALLING_AGENT_CLAIM_TTL_SECONDS = config(
    "CALLING_AGENT_CLAIM_TTL_SECONDS",
    default=300,
    cast=int,
)
CALLING_AGENT_CLAIM_BATCH_SIZE = config(
    "CALLING_AGENT_CLAIM_BATCH_SIZE",
    default=100,
    cast=int,
)
for setting_name, setting_value in (
    ("CALLING_AGENT_POLL_INTERVAL_SECONDS", CALLING_AGENT_POLL_INTERVAL_SECONDS),
    (
        "CALLING_AGENT_RECONCILE_INTERVAL_SECONDS",
        CALLING_AGENT_RECONCILE_INTERVAL_SECONDS,
    ),
    ("CALLING_AGENT_CLAIM_TTL_SECONDS", CALLING_AGENT_CLAIM_TTL_SECONDS),
    ("CALLING_AGENT_CLAIM_BATCH_SIZE", CALLING_AGENT_CLAIM_BATCH_SIZE),
):
    if setting_value <= 0:
        raise ValueError(f"{setting_name} must be greater than zero.")

CELERY_TASK_ROUTES = {
    "calling_agent.*": {"queue": "calling"},
}
CELERY_BEAT_SCHEDULE = {
    "calling-agent-claim-due-calls": {
        "task": "calling_agent.claim_due_calls",
        "schedule": timedelta(seconds=CALLING_AGENT_POLL_INTERVAL_SECONDS),
        "options": {"queue": "calling"},
    },
    "calling-agent-reconcile-scheduled-calls": {
        "task": "calling_agent.reconcile_scheduled_calls",
        "schedule": timedelta(seconds=CALLING_AGENT_RECONCILE_INTERVAL_SECONDS),
        "options": {"queue": "calling"},
    },
    "check-task-expirations": {
        "task": "users.tasks.check_and_update_task_expirations",
        "schedule": timedelta(seconds=60),
    },
    "billing-suspend-overdue-companies": {
        "task": "billing.suspend_overdue_companies",
        "schedule": timedelta(hours=1),
    },
    "billing-cleanup-pending-companies": {
        "task": "billing.cleanup_pending_companies",
        "schedule": timedelta(hours=6),
    },
}


# File Upload Settings
# Maximum size in bytes for files uploaded via forms (200MB)
DATA_UPLOAD_MAX_MEMORY_SIZE = 200 * 1024 * 1024  # 200MB
# Files larger than 100 MB are spooled to disk instead of held in RAM.
FILE_UPLOAD_MAX_MEMORY_SIZE = 100 * 1024 * 1024  # 100MB


EXCHANGE_RATE_API_KEY = config("EXCHANGE_RATE_API_KEY", default="", cast=str)
OPENAI_API_KEY = config("OPENAI_API_KEY", cast=str)

# Pinecone vector database
PINECONE_API_KEY = config("PINECONE_API_KEY", default="", cast=str)
PINECONE_INDEX_NAME = config("PINECONE_INDEX_NAME", default="", cast=str)
PINECONE_EMBEDDING_MODEL = config("PINECONE_EMBEDDING_MODEL", default="text-embedding-3-small", cast=str)

# ElevenLabs outbound calling
ELEVENLABS_API_KEY = config("ELEVENLABS_API_KEY", default="", cast=str)
ELEVENLABS_AGENT_ID = config("ELEVENLABS_AGENT_ID", default="", cast=str)
ELEVENLABS_AGENT_PHONE_NUMBER_ID = config(
    "ELEVENLABS_AGENT_PHONE_NUMBER_ID",
    default="",
    cast=str,
)
ELEVENLABS_OUTBOUND_PHONE_NUMBER = config(
    "ELEVENLABS_OUTBOUND_PHONE_NUMBER",
    default="",
    cast=str,
)
ELEVENLABS_WEBHOOK_SECRET = config("ELEVENLABS_WEBHOOK_SECRET", default="", cast=str)
ELEVENLABS_TOOL_AUTH_SECRET = config("ELEVENLABS_TOOL_AUTH_SECRET", default="", cast=str)
ELEVENLABS_TOOL_CONTEXT_TTL_SECONDS = config(
    "ELEVENLABS_TOOL_CONTEXT_TTL_SECONDS",
    default=7200,
    cast=int,
)
ELEVENLABS_TOOL_RATE = config(
    "ELEVENLABS_TOOL_RATE",
    default="60/min",
    cast=str,
)
ELEVENLABS_KNOWLEDGE_TOOL_RATE = config(
    "ELEVENLABS_KNOWLEDGE_TOOL_RATE",
    default="20/min",
    cast=str,
)
ELEVENLABS_KNOWLEDGE_TIMEOUT_SECONDS = config(
    "ELEVENLABS_KNOWLEDGE_TIMEOUT_SECONDS",
    default=8,
    cast=int,
)
ELEVENLABS_KNOWLEDGE_SCORE_THRESHOLD = config(
    "ELEVENLABS_KNOWLEDGE_SCORE_THRESHOLD",
    default=0.15,
    cast=float,
)
ELEVENLABS_TRANSFER_ENABLED = config(
    "ELEVENLABS_TRANSFER_ENABLED",
    default=False,
    cast=bool,
)
CALLING_AGENT_TOOL_CACHE_URL = config(
    "CALLING_AGENT_TOOL_CACHE_URL",
    default=CELERY_BROKER_URL,
    cast=str,
)
BILLING_CACHE_URL = config(
    "BILLING_CACHE_URL",
    default=CALLING_AGENT_TOOL_CACHE_URL,
    cast=str,
)
ELEVENLABS_API_BASE_URL = config(
    "ELEVENLABS_API_BASE_URL",
    default="https://api.elevenlabs.io",
    cast=str,
)
ELEVENLABS_REQUEST_TIMEOUT_SECONDS = config(
    "ELEVENLABS_REQUEST_TIMEOUT_SECONDS",
    default=20,
    cast=int,
)
ELEVENLABS_CALL_RECORDING_ENABLED = config(
    "ELEVENLABS_CALL_RECORDING_ENABLED",
    default=True,
    cast=bool,
)
ELEVENLABS_LIVE_TRANSCRIPT_ENABLED = config(
    "ELEVENLABS_LIVE_TRANSCRIPT_ENABLED",
    default=False,
    cast=bool,
)
CALLING_AGENT_PROMOTION_NEAR_EXPIRY_DAYS = config(
    "CALLING_AGENT_PROMOTION_NEAR_EXPIRY_DAYS",
    default=7,
    cast=int,
)
TWILIO_ACCOUNT_SID = config("TWILIO_ACCOUNT_SID", default="", cast=str)
TWILIO_AUTH_TOKEN = config("TWILIO_AUTH_TOKEN", default="", cast=str)
PUBLIC_BACKEND_BASE_URL = config("PUBLIC_BACKEND_BASE_URL", default="", cast=str)
DEFAULT_PHONE_REGION = config("DEFAULT_PHONE_REGION", default="", cast=str)

if ELEVENLABS_TOOL_CONTEXT_TTL_SECONDS <= 0:
    raise ValueError(
        "ELEVENLABS_TOOL_CONTEXT_TTL_SECONDS must be greater than zero."
    )
if ELEVENLABS_KNOWLEDGE_TIMEOUT_SECONDS <= 0:
    raise ValueError(
        "ELEVENLABS_KNOWLEDGE_TIMEOUT_SECONDS must be greater than zero."
    )
if not 0 <= ELEVENLABS_KNOWLEDGE_SCORE_THRESHOLD <= 1:
    raise ValueError(
        "ELEVENLABS_KNOWLEDGE_SCORE_THRESHOLD must be between zero and one."
    )
if CALLING_AGENT_CLAIM_TTL_SECONDS <= ELEVENLABS_REQUEST_TIMEOUT_SECONDS:
    raise ValueError(
        "CALLING_AGENT_CLAIM_TTL_SECONDS must exceed "
        "ELEVENLABS_REQUEST_TIMEOUT_SECONDS."
    )

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "axiyon-default",
    },
    "calling_agent_tools": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": CALLING_AGENT_TOOL_CACHE_URL,
        "OPTIONS": {
            "socket_connect_timeout": 2,
            "socket_timeout": 2,
        },
    },
    # Billing state MUST be shared: LocMemCache is per-process, so a webhook
    # invalidation in one worker would not reach the others. This alias points
    # at the same shared Redis instance with its own key prefix, so it needs no
    # new infrastructure. `billing.cache` degrades to a direct DB read if Redis
    # is unavailable.
    "billing": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": BILLING_CACHE_URL,
        "KEY_PREFIX": "billing",
        "OPTIONS": {
            "socket_connect_timeout": 2,
            "socket_timeout": 2,
        },
    },
}
